from enum import Enum


class TypeKode(Enum):
    PSARBMB = 'PSARBMB'
    PSBSKAT = 'PSBSKAT'
    PSRESTS = 'PSRESTS'
    LIMEDIE = 'LIMEDIE'
    POBØDPO = 'POBØDPO'
    GEOPKRÆ = 'GEOPKRÆ'
    REINDGI = 'REINDGI'
    UHFORSK = 'UHFORSK'
    UHÆGTEF = 'UHÆGTEF'
    REOPKRÆ = 'REOPKRÆ'
    PSBSKRE = 'PSBSKRE'
    VSMOMSE = 'VSMOMSE'
    PACHOKO = 'PACHOKO'
    KFDAGIN = 'KFDAGIN'
    DFDOBBE = 'DFDOBBE'
    OPREGU = 'OPREGU'
    VSARBMB = 'VSARBMB'
    REINDDR = 'REINDDR'
